sonar.projectKey=Rizdhanhr_web_testing
sonar.organization=rizdhanhr

# Nama proyek bebas yang akan tampil di halaman dasbor
sonar.projectName=Web Testing

# Versi proyek kamu (bisa disesuaikan secara berkala)
sonar.projectVersion=1.0

# Folder mana saja yang kodenya ingin di-scanning (titik "." artinya semua folder)
sonar.sources=.

# Daftarkan folder atau file yang INGIN DIABAIKAN (KECUALIKAN) dari scanning.
# Sangat penting diisi agar file library pihak ketiga atau file build tidak ikut di-scan.
sonar.exclusions=**/node_modules/**, **/.github